# Generated by Django 4.1.7 on 2023-02-28 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star5', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='empdetails',
            fields=[
                ('empid', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=30)),
                ('doj', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
                ('mobilenumber', models.IntegerField(verbose_name=10)),
                ('designation', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=128)),
            ],
        ),
    ]
