# Generated by Django 4.1.7 on 2023-02-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star5', '0007_alter_employeedetails_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='MOBILE',
            field=models.CharField(max_length=30),
        ),
    ]
