# Generated by Django 4.1.7 on 2023-02-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star5', '0004_remove_employeedetails_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='GENDER',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
