# Generated by Django 4.1.7 on 2023-02-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('star5', '0005_employeedetails_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='MOBILE',
            field=models.IntegerField(max_length=10),
        ),
    ]
